### ISSUE TITLE
Imager Interface is really cryptic and bad

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#105]
Many of the parameters that can be passed to the Imager are not clearly defined as technical or theoretical.
Also certain parameters only used for the rascil imager are in the general imager constructor to be passed, instead of the function

I suggest:
- Investigate all parameters and define if they are important
- Remove useless parameters
- Clearly define with are technical --> and try to remove all technical parameters to a different configuration, we dont want to bother users with technical details.

**Comment by deiruch** [comment]
@kenfus Do you feel this is still an issue? Should we close this?
