### ISSUE TITLE
Source Detection fails on "unphysical RMS value"

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#106]
RuntimeError: A region with an unphysical rms value has been found. Please check the input image. 
This might also be related to #103

**Comment by cvoegele** [comment]
It is not related to #103. As when the image is empty we get a different error message

RuntimeError: A region with an unphysical rms value has been found. Please check the input image.

**Comment by kenfus** [comment]
I can look at this together with #149

**Comment by kenfus** [comment]
This is hard to debug for me without any reproducable code. Source detection works generally for me, at least on two different inputs (See the two fixed notebooks in #130 )

**Comment by deiruch** [comment]
Ok, so let's close this until we find a repro case. We can always reopen.
