### ISSUE TITLE
Pinocchio: Bug in ASCII catalog output

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#113]
ASCII catalog output will always also write binary output. Appears that the curly brackets are not placed correctly:

https://github.com/i4Ds/Pinocchio/blob/821835be018ae22fc75e156fd8631ccb3473c31d/src/write_halos.c#L333-L345

**Comment by fschramka** [comment]
Fixed 

https://github.com/i4Ds/Pinocchio/commit/f09c7b82552f7f1ed5140985bc2ddb27660eb476
