### ISSUE TITLE
Integrate KatBeam and Edios for primary beam simulation for SKA-mid

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#114]
https://github.com/ska-sa/katbeam
https://github.com/ratt-ru/eidos

**Comment by cvoegele** [comment]
@rohitcbscient Katbeam and eidos packages are not available and integrated into karabo as dependencies.

**Comment by deiruch** [comment]
Edios & KatBeam output should be readable by OSKAR.

**Comment by rohitcbscient** [comment]
We aim to supply custom beams to the fit_element app. For this purpose, we want to create custom CST files. Do you have an example CST file with some documentation? We know that the cst file requires a specific format based on amplitude and phases in theta and phi coordinates. We have an electromagnetic antenna beam patterns in the farfield approximation (XY). What is the convection you use for defining theta-phi coordinates for cst file?
@rohitcbscient
**Reply**:
We aim to supply custom beams to the fit_element app. For this purpose, we want to create custom CST files. Do you have an example CST file with some documentation? We know that the cst file requires a specific format based on amplitude and phases in theta and phi coordinates. We have an electromagnetic antenna beam patterns in the farfield approximation (XY). What is the convection you use for defining theta-phi coordinates for cst file?
@rohitcbscient

**Comment by rohitcbscient** [comment]
There is an issue with the normalisation of the beam. It messes up the flux densities in the output images.
