### ISSUE TITLE
tools21cm

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#12]
UZH provides a simulation tool for 21cm radiation and simulation of foreground signals

- [ ] should we consider this package for our pipeline?
- [ ] is this kind of radiation covered with the UZH simulation of WP-C331?

**Comment by Lukas113** [comment]
UZH WP-C331 work on H1 region structures of galaxies and larger structures. They intend to cover large scale with high resolution, where currently only one of them at a time was possible.

This may be the data which ETHZ is interested in since they intend to simulate intensity mapping with SKA interferometry I think?

**Comment by deiruch** [comment]
We need this for #266 for gyro-synchrotron emission.

**Comment by Lukas113** [comment]
I was able to successfully create a [conda-package](https://anaconda.org/i4Ds/tools21cm) from `tools21cm`. However, I think it makes sense to integrate this into [Karabo-Feedstock](https://github.com/i4Ds/Karabo-Feedstock), which is why I sent the associated `meta.yaml` @fschramka . The build is tested so far that I could install and import it into a Python3.9 venv with `conda install -c i4ds -c conda-forge tools21cm`. So the `tools21cm` version `2.0.2` can be built into Karabo and then specified as dependency.

**Comment by Lukas113** [comment]
It is also important to mention that version `2.0.2` was fixed to a commit on the `master` branch. I deliberately did not choose version `2.0.1` which is the current latest version on [PyPi tools21cm](https://pypi.org/project/tools21cm/) because it depends on [cosmospectra](https://github.com/sambit-giri/cosmospectra) (very messy package which also has no Conda installation) and version `2.0.1` is also very old.

**Comment by Lukas113** [comment]
The integration into Karabo in terms of dependency resolvement worked and is integrated in PR #332 .

I think as soon as the build is integrated into [Karabo-Feedstock](https://github.com/i4Ds/Karabo-Feedstock) we can close this issue.
