### ISSUE TITLE
Implement WSCLEAN for the deconvolution

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#123]
The RASCIL imager is providing a slow and inconsistent. It would be important for both the accuracy and easy usage to integrate WSCLEAN in Karabo.
https://gitlab.com/aroffringa/wsclean/-/tree/master/

**Comment by deiruch** [comment]
WSClean is nicely packaged with Spack in http://git.astron.nl/RD/schaap-spack (Stefano Corda @ EPFL knows more, Manuel Stutz is in contact)

**Comment by deiruch** [comment]
Early tests indicate it works as a standalone package. Integration is still missing.

**Comment by rohitcbscient** [comment]
Update: Python Interface installation fails.

**Comment by kenfus** [comment]
@rohitcbscient would like some support from @fschramka

**Comment by Lukas113** [comment]
Have you looked at [radler](https://git.astron.nl/RD/radler) which is a dependency of [RASCIL](https://gitlab.com/ska-telescope/external/rascil/-/blob/0.7.1/requirements.in) ? To me it seems like this package covers our needs, however a [conda package](https://anaconda.org/) doesn't exists at the moment.

**Comment by mpluess** [comment]
> Have you looked at [radler](https://git.astron.nl/RD/radler) which is a dependency of [RASCIL](https://gitlab.com/ska-telescope/external/rascil/-/blob/0.7.1/requirements.in) ? To me it seems like this package covers our needs, however a [conda package](https://anaconda.org/) doesn't exists at the moment. Therefore, it is not usable in the current [RASCIL builds](https://anaconda.org/i4Ds/rascil/files).

The radler docs aren't exactly extensive, but seems to me like WSClean is not implemented in radler: https://radler.readthedocs.io/en/latest/tree/cpp/algorithms.html

**Comment by Lukas113** [comment]
I think you're right considering statements like 
- Radler can be installed as a stand-alone package, but is also installed as a part of `WSClean <https://wsclean.readthedocs.io>`_. If you only want to install WSClean, it is not necessary to build Radler yourself.
- Radler is a library providing functionality for deconvolving astronomical images. Radler evolved as a stand-alone library from the w-stacking clean (WSClean) imager, `https://gitlab.com/aroffringa/wsclean`_.

**Comment by mpluess** [comment]
> Update: Python Interface installation fails.

Assuming you mean this interface here: https://gitlab.com/aroffringa/wsclean/-/tree/master/interface?ref_type=heads
Seems to be outdated / not maintained. Still written for Python 2 from what I see. I managed to install it after rewriting the extension definition in _wsclean.c for Python 3 according to https://docs.python.org/3/extending/extending.html#the-module-s-method-table-and-initialization-function. But then you get the next Python 3 incompatibility when importing it.

Best option to me seems to write our own little Python wrapper for the CLI command.

**Comment by sfiruch** [comment]
#519 tracks transition to newer Python versions. Should be prioritize?

**Comment by mpluess** [comment]
I tried again to get a dev environment with wsclean up and running, haven't succeeded so far. The problem is not the Python version, but this dependency in the wsclean conda package: `boost-cpp >=1.74.0,<1.74.1.0a0`
We're using boost 1.82.

Best option is probably to create our own wsclean conda package. Also means we can use the latest wsclean release.

To answer Simon's question: no need to prioritize #519 because of wsclean.

**Comment by Lukas113** [comment]
I agree to build our own wsclean conda package. The available conda-wheel is outdated as mentioned, and it only has one build, which means only a single boost-version is supported.
