### ISSUE TITLE
Installation on macOS: Environment can't be created

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#125]
it is bundled now - but the conda environment cant be created on macos - will further investigate this.

_Originally posted by @fschramka in https://github.com/i4Ds/Karabo-Pipeline/issues/65#issuecomment-1219646820_

**Comment by deiruch** [comment]
libmamba should give you better reports. https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community

**Comment by deiruch** [comment]
Is this still a problem?

**Comment by fschramka** [comment]
Rascil 0.5 can not be installed on macos. 

it seems to have issues with bdsf.

**Comment by fschramka** [comment]
We found the error in bdsf - there is no working macos build for python 3.9 - the version we use in karabo. @cvoegele removed macos 3.9 support, why?

**Comment by cvoegele** [comment]
I guess the build wasn't working for 3.9 so i stopped cause at the time we were still mainly targeting python 3.8

**Comment by fschramka** [comment]
Bdsf currently does not work with Python 3.9 - This is a stripped down build process on macOS:
https://github.com/i4Ds/bdsf-build/actions/runs/3220846844/jobs/5268067941#step:5:243

The fortran compiler seems to have an issue.

**Comment by kenfus** [comment]
@patoch01220 is also trying to install PyBDSF on macos, maybe there is something helpful here:

https://github.com/lofar-astron/PyBDSF/issues/183

**Comment by patoch01220** [comment]
> Bdsf currently does not work with Python 3.9 - This is a stripped down build process on macOS: https://github.com/i4Ds/bdsf-build/actions/runs/3220846844/jobs/5268067941#step:5:243
> 
> The fortran compiler seems to have an issue.

I did succed installing it with python 3.9.13, but still have problems when using it.
I also tried installing it on a conda env with python 3.10 and 3.8 but both didn't work.

**Comment by deiruch** [comment]
From https://github.com/i4Ds/Karabo-Pipeline/issues/167#issuecomment-1278840016:

> I have to following message:
> ```
> (karabo-env) patoch@patricks-mbp-1 ~ % conda install -c i4ds -c conda-forge karabo-pipeline
> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: / 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                          
>
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> ```

**Comment by fschramka** [comment]
bdsf fixing will be documented here:
https://github.com/i4Ds/Karabo-Pipeline/issues/205

**Comment by deiruch** [comment]
We will drop macOS support (i.e. stop trying to support macOS). Cost/reward is unfortunately not looking good enough.
