### ISSUE TITLE
A specific python version is installed when installing karabo with conda.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#129]
When installing karabo, the python version is not defined. This leads to an error when opening a notebook with vscode because somehow it does not know which python version it is and wierd stuff happens (unable to install ipython via vscode-popup and constant error messages, such as "this python version does not support ipython").

I think this is a vscode problem but it is still widely used.

![grafik](https://user-images.githubusercontent.com/47979198/187921875-f380efa0-42a0-4fdf-8933-452585a71493.png)
Top: Fixed meta.yaml
Bot: Unfixed meta.yaml

Suggestion: Decide and stick to a python-version and put it in the `meta.yaml` file.

**Comment by kenfus** [comment]
@Lukas113 How should be proceed with this one? On my new laptop I had no problem not defining a python version anymore.

**Comment by deiruch** [comment]
@kenfus I think this is fixed now, no?
