### ISSUE TITLE
Documentation for Software/Algorithm developers

### ISSUE THREAD

**Issue by sfiruch** [i4Ds/Karabo-Pipeline#13]
We should make sure that developers on other teams have a smooth entry when they work with our code.

Brief explanations how Karabo can be extended with new
- [ ] Data sets
- [ ] Imaging algorithms
- [ ] Source Detection algorithms
- [ ] RFI/noise simulations

**Comment by deiruch** [comment]
Yeah, a lot is there. But I think there is still one important piece missing: We should document which functionality can easily be added: Imaging algorithms, RFI simulations, source detection algorithms, new data sets, etc. - with pointers how to start for each one.

**Comment by Lukas113** [comment]
I think this is already shown by existing notebooks and should be covered when #583 is taken care of. At least for functions we already provide. Otherwise I would consider it as an API extension issue, not doc. Therefore closed.

**Comment by sfiruch** [comment]
We should reconsider, once we have external devs wanting to extend Karabo.
