### ISSUE TITLE
Define orientation of matrices

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#137]
Currently, in packages (such as scipy, XGBoost or scikit-learn), points in 2D are saved in the numpy array as rows (Shape: `nx2`). However, some parts of Karabo work with points in 2D as columns (`2xn`). 

Maybe there is a performance-related reason to do it one way or the other?

**Comment by deiruch** [comment]
> Maybe there is a performance-related reason to do it one way or the other?

Don't think so. I think it'd be worthwhile to make it consistent.

**Comment by deiruch** [comment]
To me personally, points as rows feels more natural. Probably caused by years of looking at SQL tables... :)

The sooner we make this consistent, the better.
