### ISSUE TITLE
Karabo installation fails with Python 3.8

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#141]
I think we can place installation related issues:

I encountered the following install issues of Karabo v0.8.0:
    
Installation:
    - localhost (Ubuntu 20.04):
        user install:
            python=3.8 FAILED
                - feature:/linux-64::__glibc==2.31=0
                - python=3.8 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
                Your installed version is: 2.31
            python=3.9.13 FAILED
                - feature:/linux-64::__glibc==2.31=0
                - feature:|@/linux-64::__glibc==2.31=0
                Your installed version is: 2.31
        dev install:
                install using "environment-dev.yaml" SUCCEEDED (python=3.9.13)
    - cscs (daint):
        user install:
            python=3.8 FAILED
                - feature:/linux-64::__glibc==2.26=0
                - python=3.8 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
                Your installed version is: 2.26
            python=3.9.13 SUCCEEDED
        dev install:
            install using "environment-dev.yaml" SUCCEEDED (python=3.9.13)

**Comment by deiruch** [comment]
Related to #129

**Comment by fschramka** [comment]
on a macos system:

> conda create -n karabo-env python=3.9.13
> conda activate karabo-env
> conda install -c i4ds -c conda-forge karabo-pipeline

`--> UnsatisfiableError: The following specifications were found to be incompatible with each other: `

**Comment by fschramka** [comment]
Even without forcing the version it does not work on macos. Will check this :)

**Comment by deiruch** [comment]
We'll update to newer versions anyway. E.g. 3.9 and newer. macOS builds are broken at the moment, this is tracked in #49.
