### ISSUE TITLE
Tests should also run on WSL

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#148]
Currently, the pipeline is only tested on each push on ubuntu 20.04. However, the installation on WSL is not tested.

**Comment by deiruch** [comment]
Not sure this is too useful: WSL (can) run Ubuntu 20.04 (and other distributions). So the environment should be identical to any other VM running Ubuntu 20.04.

I think testing multiple distros might make more sense? Do you think focusing on that would be important?

**Comment by kenfus** [comment]
- We decided to close this because ubuntu 20.04 is already included in our tests and technically it should be identical to the installation under wsl.
