### ISSUE TITLE
Fix h5py to 3.1

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#153]
Our manual https://i4ds.github.io/Karabo-Pipeline/installation_user.html states that users should up/downgrade to h5py version 3.1. We should make sure that the correct version 3.1 is installed by default.

Simlar to #129 and #147

**Comment by kenfus** [comment]
I just rested this and this can be closed because the error appears only if `gsl` is not (correctly) installed. Also, nobody else had the error with `h5py`.
