### ISSUE TITLE
RASCIL 0.7.1

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#157]
Setup of RASCIL new release
For this I have to build conda packages for 
- seqfile: https://github.com/musically-ut/seqfile
- ska-sdp-func: https://github.com/ska-telescope/ska-sdp-func

Another, not fixed package is "radler", but it doesn't seem to be important.

**Comment by Lukas113** [comment]
The seqfile package is now available at: https://anaconda.org/i4ds/seqfile

**Comment by Lukas113** [comment]
This issue is depends on #164 . As soon as an anaconda package of `ska-sdp-func` is available, I can try to rebuild and run the Unittest afterwards.

**Comment by kenfus** [comment]
@Lukas113 will give @fschramka access to the repository in which Lukas is working right now.

**Comment by Lukas113** [comment]
@fschramka I've added you and Simon as Admins to https://github.com/i4Ds/ska-sdp-func-build

As mentioned in the meeting the build with the python bindings doesn't work yet and I haven't tested anything with mac.

**Comment by deiruch** [comment]
> [...] and I haven't tested anything with mac.

FYI: We will drop macOS support (i.e. stop trying to support macOS). Cost/reward is unfortunately not looking good enough.

**Comment by Lukas113** [comment]
`ska-sdp-func 0.0.3` is now available at [Anaconda registry](https://anaconda.org/i4ds/ska-sdp-func). Thus as soon as @fschramka finished refactoring the RASCIL build (see #216 ) `RASCIL 0.7.1` should be ready to build.

**Comment by fschramka** [comment]
@Lukas113 go for it :)

**Comment by Lukas113** [comment]
I've tried to build a `0.7.dev1` version on the according branch and got the following error:

![image](https://user-images.githubusercontent.com/32157249/208921075-bca9ed14-c740-44fc-9063-f64631580045.png)

Currently I'm not sure how to solve or approach it since I haven't found something useful on the internet. However, this issue must be related to `ska-sdp-func` (maybe also the build? Not sure, but `conda install `conda install -c i4ds -c conda-forge ska-sdp-func` itself works) since it occurs only after adding this specific dependency (e.g. RASCIL build `0.7.0` still works in the same environment).

**Comment by fschramka** [comment]
we will directly go to https://github.com/i4Ds/Karabo-Pipeline/issues/233
