### ISSUE TITLE
Setup Package Versioning

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#158]
Setup of different branches of builds of Karabo dependency builds we do ourself.
With this, we should be able to support bugfixes and builds of different versions.

**Comment by deiruch** [comment]
Can you coordinate with @kenfus to update the release manual accordingly?

**Comment by Lukas113** [comment]
Ok. I will talk to him.

**Comment by Lukas113** [comment]
I've done it for the rascil-build (see https://github.com/i4Ds/rascil-build). I think it might also be useful to do it for oskar builds since we use 2.8.0 and the latest release is 2.8.3. What do you think about that @deiruch ?

**Comment by Lukas113** [comment]
Setup for RASCIL and OSKAR is done and works.
