### ISSUE TITLE
Merge binaryIO work into main

### ISSUE THREAD

**Issue by sfiruch** [i4Ds/Karabo-Pipeline#159]

**Comment by deiruch** [comment]
Just merge the utility functionality, so that it'd be easier to fully support the file format in the future.

**Comment by fschramka** [comment]
has already its own branch - but not rdy yet to use

**Comment by deiruch** [comment]
@fschramka Any progress on this? What is missing?

**Comment by fschramka** [comment]
Just half of a random implementation is there - requirements are also bit unclear.

**Comment by deiruch** [comment]
@rohitcbscient Do you still need the binaryIO work? I thought I vaguely remember hearing something?

If you don't need it anymore, feel free to close this issue and the corresponding branch.

**Comment by Lukas113** [comment]
@sfiruch still sth to address? There is no clear description of this issue and no progress since a year. If not depicted further, I plan to close this issue as stale.
