### ISSUE TITLE
build Anaconda package ska-sdp-func

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#164]
RASCIL 0.7.1 depends on https://github.com/ska-telescope/ska-sdp-func and throws an Error. Since it is not available anywhere other than GitHub, we need to build an Anaconda package. This is a C++ library. This is related to #157.

**Comment by deiruch** [comment]
@Lukas113 Can you detail the error it produces?

**Comment by Lukas113** [comment]
![image](https://user-images.githubusercontent.com/32157249/195120005-273b2b68-2ebd-46ee-bfd2-b063f63c31ff.png)

**Comment by Lukas113** [comment]
That's the output I get when I run the build command `conda mambabuild -c i4ds -c conda-forge .` of `rascil-build/conda` and set `export VERSION=0.7.1` (no other changes than `0.7.0` which works) previously in the docker container `ghcr.io/i4ds/mambabuild-docker:latest` where the build on GitHub Actions is happening.

**Comment by Lukas113** [comment]
Build succeeded (finally :) and is available through the i4ds conda channel. [Here](https://github.com/i4Ds/ska-sdp-func-build) is a link to the build repository.
