### ISSUE TITLE
Provide benchmarking script for SCOOP

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#168]
@UeliDeSchwert offered to take Karabo into their benchmarking pipeline. However, to do this, we should create a python script and make it available.

**Comment by UeliDeSchwert** [comment]
Optimally, to be able to run Karabo within the scope of SCOOP's benchmarking suite there would exist a number of runnable files that run a specific workload. We would then base the run-scripts that we use on the run-scripts you develop, as we need to add some additional stdout-outputs, especially for the exact timing of function calls. 

No work to add Karabo to the ska-sdp-benchmark-suite has been planned for PI16, but it would be a valuable addition during the course of PI17, starting in december.

**Comment by deiruch** [comment]
@UeliDeSchwert Do we need to supply all runnable files/workloads at once, or can we add more incrementally?

**Comment by UeliDeSchwert** [comment]
Incrementally is absolutely fine :+1:

**Comment by deiruch** [comment]
@fschramka Do you think it'd take much to reuse the PINOCCHIO workload you prepared for CSCS ?

**Comment by kenfus** [comment]
We currently can run all the tests with `result = karabo.utils.testing.run_tests()` and have an `assert test_result.wasSuccessful()`. This could already be a start for the benchmark testing.

**Comment by deiruch** [comment]
#266 and #170 workloads should be considered as well. @fschramka can you make sure that they get a useful benchmark?

**Comment by fschramka** [comment]
Sure :)

**Comment by kenfus** [comment]
@fschramka I have created this for the GPU scaling testing: https://github.com/i4Ds/Karabo-Pipeline/blob/VT_284-scaling-for-karabo-gpu-implementation/karabo/examples/time_karabo.py

Maybe this is helpful to you for this issue?

**Comment by deiruch** [comment]
@UeliDeSchwert is this integrated in SCOOP? Can we support the effort?

**Comment by UeliDeSchwert** [comment]
This is planned for PI19 as a Spike. So I'll be integrating a basic Karabo test into the benchmarking suite during the coming weeks / months. 

Is the file linked by @kenfus [here](https://github.com/i4Ds/Karabo-Pipeline/issues/168#issuecomment-1443780356) a basic workload that should run easily and give a good overview of the performance of Karabo?

**Comment by deiruch** [comment]
@UeliDeSchwert I think https://github.com/i4Ds/Karabo-Pipeline/blob/VT_284-scaling-for-karabo-gpu-implementation/karabo/test/test_pinocchio.py would be better.

@fschramka Can you explain Manuel how to scale up the Pinocchio config so that it uses "a bit" of memory and the whole thing takes an hour or so? And should we combine it with `PyBDSFSourceDetectionResult.detect_sources_in_image(dirty)`?

**Comment by fschramka** [comment]
@deiruch This should come from ETH. Increasing all numbers is a good start - but that may be bit random

**Comment by deiruch** [comment]
@lmachadopolettivalle Can you help with an interesting Pinocchio configuration for benchmarking?

**Comment by lmachadopolettivalle** [comment]
Do we still need this issue? Closing for now, but can be reopened if still necessary.
