### ISSUE TITLE
Intercept impossible values for Oskar

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#169]
#135 was caused by wrong noise-parameters given to Oskar, even though Noise was set to false in Oskar (at least it was fixed by changing the parameters to something plausible). So it would be great to warn the user generally when he is using impossible parameters for Oskar.

**Comment by Lukas113** [comment]
I think checking for value errors should be a general pursue. And since this issue is stale, I'll close it.
