### ISSUE TITLE
Integrate Philipp Denzel's "Simulated-Light-Cones-To-Sky-Model" code

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#171]
Apparently, Philipp is working on code to convert simulated light cones to sky models. We could use that code to make integration of simulation outputs possible. Perhaps we could integrate his work?

**Comment by phdenzel** [comment]
Lightcones are often not available for the kinds of simulations I use... for now, I'm working on loading single SPH simulation snapshots into karabo/oskar. I'm happy to contribute, once I have something workable ;)

**Comment by rohitcbscient** [comment]
Hydro codes makes the snapshots not light cones, we have light cones for Pinnochio simulations.
