### ISSUE TITLE
Push Pinocchio changes to pigimonaco/Pinocchio fivedotzero

### ISSUE THREAD

**Issue by fschramka** [i4Ds/Karabo-Pipeline#172]
Create pull requests for pinocchio that solve the compiler problems.

**Comment by fschramka** [comment]
done https://github.com/pigimonaco/Pinocchio/pull/4

**Comment by pigimonaco** [comment]
thanks for the fixes!

**Comment by fschramka** [comment]
@pigimonaco 

you are welcome - thanks for the library! 

I also enlarged the input file buffer and did a conda workflow. Few fixes needed by ethz will be added soon. I forked your repo to do those: https://github.com/i4Ds/Pinocchio/tree/fivedotzero

I will create pull requests for everything I do :)
