### ISSUE TITLE
SourceDetectionResult.detect_sources_in_image does not run for a very long time.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#176]
In `source_detection.ipynb`, when running 

```
detection_result = SourceDetectionResult.detect_sources_in_image(restored)
detection_result.detected_sources
```

the algorithm runs for a very long time and then seems to timeout the kernel, without giving any error. However, my CPU usage is above 50% for more than 3 hours. I think I need to have a look at it together with @rohitcbscient .

**Comment by deiruch** [comment]
Apparently depends on parameters. We should analyze it, to understand what the problem is.

Can we help users to not fall into this trap?

**Comment by deiruch** [comment]
Did anything come out of the analysis with @rohitcbscient ?

**Comment by kenfus** [comment]
For me, we can close this @deiruch. I did not encounter this anymore.
