### ISSUE TITLE
GPU-acceleration in OSKAR

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#180]
#134 is currently blocked because our simulations are not fast enough, even on CSCS. OSKAR is currently running in a CPU-only configuration. We need a way to distribute Karabo that supports both CPU-only and GPU-accelerated versions of our dependencies.

Options:
a) Build dependencies in such a way that they pick the right version at runtime
b) Build dependencies in multiple configurations, Karabo ships with both dependencies, and Karabo decides at runtime which dependency to run.
c) Build from source on every installation

Option b) might be easier to set up, option a) would be easier for all non-Karabo users. Option c) is something that Victor (CSCS) is working on but probably not the right solution for general distribution.

**Comment by deiruch** [comment]
Perhaps a build compiled with CUDA- & OpenCL-support could be used on all machines after all?

https://ska-telescope.gitlab.io/sim/oskar/settings/settings-simulator.html suggest there's a runtime configuration switch. But perhaps it only allows users with CUDA to temporarily disable CUDA. It's likely that a CUDA-build wouldn't work on non-CUDA machines, despite disabling it in the configuration file.

**Comment by kenfus** [comment]
I tried to find out exactly where we chose to build oskar without CUDA support. Do we know this? I found this:
```
#mkdir -p $PREFIX
#cmake -DCFIND_CUDA=OFF -DCUDA_ARCH="3.5;3.7;5.0;5.2;6.0;6.1;6.2;7.0;7.5" -DNVCC_COMPILER_BINDIR=$CXX -DCMAKE_INSTALL_PREFIX=$PREFIX
# for some reason without the extra LICENCE call the build tells that it doesn't exists and thus fails
wget https://github.com/OxfordSKA/OSKAR/blob/master/LICENSE

pkgv=$(sed 's/dev//g' <<< "$PKG_VERSION")

mkdir tmp
cd tmp
git clone --branch "$pkgv" https://github.com/OxfordSKA/OSKAR.git .
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX
make -j install
cd ..
rm -rf tmp
#
#export OSKAR_INC_DIR=$PREFIX/include
#export OSKAR_LIB_DIR=$PREFIX/lib
#
#cd $SRC_DIR/python && $PYTHON -m pip install .  -vv
```
from https://github.com/i4Ds/oskar-build/blob/master/oskar-base/conda/build.sh

I am not sure why so much is commented out. Did we ever try to just build it with CUDA enabled and see what happens if we use `use_gpu` in Oskar as following:
```
        setting_tree = oskar.SettingsTree("oskar_sim_interferometer")
        if use_gpu:
            settings1 = {**settings1, **{'simulator/use_gpus': use_gpu}}
        setting_tree.from_dict(settings1)

```

**Comment by phdenzel** [comment]
CUDA builds of karabo/OSKAR/RASCIL on CPU-only machines work for me (finally). `use_gpus` needs to be set to `False` at runtime to avoid errors though.
On a side note (for future builds): I found that installing rascil, in particular ska-sdp-func, has an issue when CUDA >=11.6 and compiled with GCC 12. Installing and compiling ska-sdp-func manually with GCC 11 seems to work. Has anybody observed similar problems?

**Comment by kenfus** [comment]
I also found this to install cuda on github hosted instances: https://github.com/Jimver/cuda-toolkit

Maybe we could just prebuild karabo with cuda and gpu support?

**Comment by deiruch** [comment]
Yeah, that sounds reasonable. Should we do something with OpenCL? Wonder how many users there are that are using AMD cards. Perhaps something to worry about later. If we could quickly get a Cuda version running, that'd be amazing.
