### ISSUE TITLE
Root-Cause-Analysis of flaky docker image builds

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#188]
Why was todays image not working ("/data" bug)?
Are our public user images also affected by the same issue?

**Comment by Lukas113** [comment]
I've checked the log files of `attempt \#1` and `attempt \#2` of the [docker build action](https://github.com/i4Ds/Karabo-Pipeline/actions/runs/3342601514). The only difference between the failed and successful build were the `5_Build and push Docker image.txt` logs. Sadly, I couldn't conclude anything meaningful from it.

**Comment by Lukas113** [comment]
close this issue @deiruch ? I'm not sure how to approach this any differently than I have been doing.

**Comment by deiruch** [comment]
We should reopen the issue when it occurs again.
