### ISSUE TITLE
Investigate worker file access solutions

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#19]
When using a distributed cluster, all workers must also be able to get certain files. For example for the rascil_imager the workers need the ms file on their file system. When working locally you can just set the directory.

However for actual distributed clusters some solution would be good, also because current api's from dask for uploading files to the workers are not satisfactory. 
For example client.upload_file uploads a file to all workers, however this is first of all slow if there are too many workers and an ms file is a directory so it cannot be uploaded with this function.

Maybe we need more functions , like upload directory (recursive file upload) or some sort of a better distributed file system integration?

**Comment by deiruch** [comment]
Closing for now. We can re-open when we hit scalability problems on CSCS.
