### ISSUE TITLE
Create a similar function to `evaluate_result_with_sky_in_pixel_space` but with RA and DEC.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#194]
Currently, `evaluate_result_with_sky_in_pixel_space` uses "pixel space" and I feel this is hard to understand in reality. How much is really one pixel distance? Or 10? Should this not be calculated in RA and DEC?

**Comment by deiruch** [comment]
@rohitcbscient @jejestern What do you think as domain experts? Is this desirable/needed?

**Comment by jejestern** [comment]
@kenfus Where/In which file is this function situated?

**Comment by jejestern** [comment]
We receive the same plot in RA/DEC by using explore_sky.

**Comment by deiruch** [comment]
@kenfus Would additional documentation help? If so, can you change the documentation - otherwise feel free to re-close the issue again.
