### ISSUE TITLE
The code is written in a way that it's usage makes sense from a science standpoint

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#198]
Some things, e.g. `BeamPattern` can probably be combined because for the `BeamPattern` we always give X and Y, so there is no point in making two separate objects.

**Comment by deiruch** [comment]
Please do a review of all our public API.

**Comment by deiruch** [comment]
@rohitcbscient Did you have time to review this?

**Comment by deiruch** [comment]
@rohitcbscient Do you have any updates?

**Comment by rohitcbscient** [comment]
The beam issue is being tackled in #301. We will change the API once the beam is working correctly.
The other issues are as follows:

- [ ] Allow selecting all pyBDSF parameters for parametric studies. May be introduce kwargs in source detection.
- [ ] source detected coordinates must return both pixel and ra,dec coordinates.
- [ ] get_pixel_position_of_sources() returns (2, number of sources
detected) which would be more intuitive the other way around: (number of sources detected, 2). Change the shape of the output.
