### ISSUE TITLE
A general code style is chosen

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#199]
Currently, there are many different styles existing in this project and this should not be. Also, we should we all use the same linter.

@fschramka suggested https://dev.to/adamlombard/how-to-use-the-black-python-code-formatter-in-vscode-3lo0

**Comment by deiruch** [comment]
Maybe use https://editorconfig.org/ ?

**Comment by deiruch** [comment]
Perhaps we can find something that would enforce/strongly suggest type annotations as well?

**Comment by kenfus** [comment]
I am currently using `flask8` together with Pylinter. I also refactored our code. However, this was my first encounter with black: https://github.com/i4Ds/Karabo-Pipeline/actions/runs/3658543650

- it disabled all unittests

**Comment by deiruch** [comment]
Changes should go in 2023-01-23

**Comment by deiruch** [comment]
Perhaps also force type annotations? (see #191)
