### ISSUE TITLE
Add source detection and benchmarking metrics

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#20]
Research of existing source detection packages to detect sources in the deconvolved images.
Also add possibility to benchmark the source detection. Research existing benchmark metrics for source detection

- [x] Implementation
- [x] Use telescope module
- [x] Package imaging
- [x] Package sky model
- [x] WCS conversion without image generation
- [x] implement automatic source assignment of predicted sources with ground truth
- [x] Imaging
- [x] Source detection (https://www.astromatic.net/software/sextractor/ or PyBSDF)
- [ ] #87
- [ ] #92

**Comment by Lukas113** [comment]
I've made a document https://swiss-ska.fhnw.ch/index.php/f/15423 (internal link) that shortly describes the source detection task and that proposes some possible implementations on how our pipeline could contribute to this matter.

Next I will work to simulate random sources with OSKAR and try to create a .fits file out of it. 

In addition, I try to provide both, celestial and image coordinates from the sources as catalogue.

**Comment by Lukas113** [comment]
Right now there is an example notebook which takes the MWA GLEAM survey catalogue as input, filter it, make an image and provides the image pixels of the sources as output.

Currently this is not well integrated in the pipeline, so I'm working on that.

**Comment by Lukas113** [comment]
Currently getting the pixel coordinates of an image from a catalogue is now possible without performing any simulation using the Pipeline. This is not yet properly tested and it is still in the object_detection branch.

**Comment by Lukas113** [comment]
I've setup a source detection benchmark notebook where I have written an outomatic assignment of the predicted and the ground truth sources. It also has the calculation of TP, FP and FN in it. It is not well integrated in the framework yet and it is all on the source_detection framework at the moment.

**Comment by deiruch** [comment]
We can host benchmark data on https://user.cscs.ch/storage/object_storage/ and automatically download it when the benchmark runs. Can you filter the relevant part of GLEAM and store that subset?

**Comment by deiruch** [comment]
Users from sk05 should now be able to go to [castor.cscs.ch](http://castor.cscs.ch/) and manage the object storage from there. Docs are here: https://user.cscs.ch/storage/object_storage/

**Comment by cvoegele** [comment]
@deiruch How can i become a user of sk05?

**Comment by deiruch** [comment]
Just can ask Victor Holanda on Slack, he usually responds very quickly.

**Comment by cvoegele** [comment]
@deiruch Victor Holanda said, he cannot add me to sk05. Only the owner of that group can add new people. And that should be you?

**Comment by deiruch** [comment]
> @deiruch Victor Holanda said, he cannot add me to sk05. Only the owner of that group can add new people. And that should be you?

You should have a reply from Lukas.

**Comment by cvoegele** [comment]
Current Status. Source detection can be run and displayed on the current image.
![image](https://user-images.githubusercontent.com/10659582/171025193-72fa2849-3c7c-4293-8228-b56fcb456d5c.png)

**Comment by deiruch** [comment]
Nice! (looks as if the image is scaled slightly differently than the points)
