### ISSUE TITLE
Unit test for creating mock MIGHTEE survey

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#200]
Using MIGHTEE source catalog, create a mock SKA MIGHTEE survey.

**Comment by rohitcbscient** [comment]
The cscs link for mightee does not work: https://object.cscs.ch/v1/AUTH_1e1ed97536cf4e8f9e214c7ca2700d62/karabo_public/download/MIGHTEE_Continuum_Early_Science_COSMOS_Level1.fits

**Comment by Lukas113** [comment]
To me it seems like the path is not correct. The path that worked for me is:

https://object.cscs.ch:443/v1/AUTH_1e1ed97536cf4e8f9e214c7ca2700d62/karabo_public/MIGHTEE_Continuum_Early_Science_COSMOS_Level1.fits

**Comment by Lukas113** [comment]
The path is `{CSCS-object-store-prefix}/{Container}/{Object}` where the prefix comes from [CSCS API access](https://castor.cscs.ch/dashboard/project/api_access/).

**Comment by deiruch** [comment]
@rohitcbscient Do you have updates?
