### ISSUE TITLE
MIGHTEE survey available on CSCS

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#201]
The cscs link for mightee does not work: https://object.cscs.ch/v1/AUTH_1e1ed97536cf4e8f9e214c7ca2700d62/karabo_public/download/MIGHTEE_Continuum_Early_Science_COSMOS_Level1.fits

_Originally posted by @rohitcbscient in https://github.com/i4Ds/Karabo-Pipeline/issues/200#issuecomment-1311413451_

**Comment by Lukas113** [comment]
See #200 , the path seems to be not correct. Maybe they've changed it?

**Comment by rohitcbscient** [comment]
#200 requires the link to work for the mightee survey sky models.
