### ISSUE TITLE
Build Dev Env is able to echo enviroment variables from environment-dev.yaml

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#203]
As seen in PR #202, the github action `Build Dev Env` is unable to create enviroment variables from environment-dev.yaml. This is important because to make use of the GPU in rascil, the following variable needs to be set when using WSL:

`LD_LIBRARY_PATH: /usr/lib/wsl/lib`

**Comment by Lukas113** [comment]
I've added a fix in karabo's root __init__.py where I extend/create  `LD_LIBRARY_PATH` if the platform is WSL. Can you test it in the branch `LG_201_ld_library_path` @kenfus ?

**Comment by Lukas113** [comment]
I think we can close this issue since [LG_201_ld_library_path](https://github.com/i4Ds/Karabo-Pipeline/commit/15d45755d6a068483963431f1522789926d431fc) should have fixed it @kenfus ?
