### ISSUE TITLE
`SourceDetectionResult.get_pixel_position_of_sources()` returns pixel values

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#208]
Currently, as mentioned by Patrick Arlt, it returns real numbers and not integers.

**Comment by Lukas113** [comment]
The reason it returns float and not integer values is that float values are much more accurate when the pixel size is coarse. In the extreme case, integer values would assign multiple sources to a pixel, losing essential information.

Should we tackle this issue anyway? I see the following possibilities:

- Keep functionality, but set docstrings and return values so far that it should be clear that a float is returned.

- Return real pixel values, changing the relative positions to each other and also aggregating multiple sources to one, depending on pixel sizes.

- Implement both options mentioned above and make them available through a parameter or two different functions.

What is your opinion on this @rohitcbscient @deiruch ?
