### ISSUE TITLE
Rascil Build: Integrated test is broken

### ISSUE THREAD

**Issue by fschramka** [i4Ds/Karabo-Pipeline#216]
Rascil build will fail in the install & test phase:

https://github.com/i4Ds/rascil-build/actions/runs/3608642833/jobs/6081448458

The 0.7.dev0 branch uses the new pybdsf build.

**Comment by Lukas113** [comment]
@fschramka I will look into it.

**Comment by fschramka** [comment]
Started to refactor the rascil build

**Comment by fschramka** [comment]
https://github.com/i4Ds/rascil-build/actions/runs/3658783594

refactored rascil build with the new pybdsf branch is deployed. 

local test with python 3.9:
conda install -c i4ds -c conda-forge karabo-pipeline --experimental-solver=libmamba

solved the environment in ~20s
installed it in ~1min (maybe with cached items)
