### ISSUE TITLE
The tests on github use the current version of dev-env.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#227]
Currently, our testing on push only works on a docker-container created during the night from the main branch. Thus, if we change a dependency or introduce a new package, this is not tested because the image is created on the main branch and not the branch we are currently working on. 

I think there are two solutions:

- we don't cache the environment at all, we rebuild the environment on every push. Currently, building and uploading the image takes around 30 minutes. Is this too long to wait? I think it's OK, the big testing should be done locally anyway and maybe with mamba this will actually be quick.
- people need to manually trigger the creation of the cached environment from their branch and use it. However, this means that someone else is maybe testing with a wrong cached environment. 

@Lukas113 @deiruch @fschramka any input?

**Comment by deiruch** [comment]
Do I get it right: This means we currently get feedback after the PR was merged, if we break Docker? If so, I suggest we lower the priority of this issue. It's not as if we're adding new dependencies every other day, and break Docker.

If we decide to solve this problem, I'm strongly in favor of the first option. Slower automation is preferrable to manual intervention.

**Comment by kenfus** [comment]
@Lukas113 @deiruch We discussed that dev-env for testing can RIP. In addition, we will only have one docker container: `user` with a clean jupyter-notebook (such as source-detection.ipynb) to get started.

This container should also be tested on release and maybe built on the weekend and run on cscs.
