### ISSUE TITLE
astropy 5.2 ModuleNotFoundError

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#232]
I've setup a new environment using `environment-dev.yaml` and encountered a `ModuleNotFoundError: No module named 'astropy._erfa'` Error when `import rascil` (`rascil==0.7.0) was called. This was caused by `astropy` where the version was `astropy==5.2` (release 12.12.2022). However, as soon as I've downgraded to `astropy==5.1.1` the error didn't occur anymore.

Since the error is thrown through RASCIL I think we should specify the version also in the RASCIL build (and if possible not in  `environment-dev.yaml`). In addition, we have to check whether it is also an issue in RASCIL 0.7.1 #157 )

**Comment by Lukas113** [comment]
![image](https://user-images.githubusercontent.com/32157249/207357224-526a2c54-9dac-4a3a-91fb-da502a567f93.png)

**Comment by kenfus** [comment]
This is now updated via Rascil and #236 will include the removal of astropy as dependency in Karabo. The version of astropy will be defined only in our rascil-build.

**Comment by Lukas113** [comment]
Nice. I merged the PR and therefore close this issue.
