### ISSUE TITLE
SkyModel.explore_sky() needs additional parameters 

### ISSUE THREAD

**Issue by jejestern** [i4Ds/Karabo-Pipeline#234]
SkyModel.explore_sky() misses some optional parameters:

- vmin and vmax, currently they are set to None. The user needs to be able to set these values differently in order to investigate the data
- plot is in wcs coordinate system, but what if the user wants to look at the data in the original coordinate system, in which he entered the data? It should be possible to choose  wcs=enabled/disabled
- add an additional parameter: plt.savefig('title'), s.t. the user can save the plot if he wants

**Comment by Lukas113** [comment]
I've made the according changes in the branch `LG_203_address_unige_report`. I'm not completely sure if it makes sense how I implemented `wcs_enabled=False`. I just excluded the conversion and all resulting variables to produce the plot. I think I can make a PR soon (there are also other api changes in this branch).
