### ISSUE TITLE
CUDA runtime dependencies are slimmed down

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#235]
Currently, we install approx. 2.8GB dependencies, because of CUDA. Most of the cuda things (NSight, etc.) are not really required for our use case. Perhaps we can only install the strictly required subset to reduce the install size and time.

Probably many lib* are required, but UI tools are most certainly not required.

**Comment by kenfus** [comment]
Sadly, you are unable to define channels in the meta.yaml for the package-building as described here: https://github.com/conda/conda-build/issues/532#issuecomment-410244068

This means that because nvidia is using channels for their versioning, our installation for karabo will look something like this: 

`conda install -c i4ds -c conda-forge -c nvidia/label/cuda-11.7.0 karabo-pipeline`

**Comment by deiruch** [comment]
> Karabo gets bigger and bigger due to more functionallity.
> 
> Here is the top 10:
> 
> 1. nsight-compute-2022.2.0.13-0.json:                      "size":  485381969,
> 2. libcublas-dev-11.10.1.25-h0c8ac2b_0.json:            "size":  324267418,
> 3. libcusparse-dev-11.7.3.50-hc644b96_0.json:         "size":  315781272,
> 4. libcublas-11.10.1.25-he442b6f_0.json:                   "size":  314450443,
> 5. libcufft-dev-10.7.2.50-h59a5ac8_0.json:                "size":  205997732,
> 6. libcusparse-11.7.3.50-h6aaafad_0.json:                  "size":  155592022,
> 7. libnpp-11.7.3.21-h3effbd9_0.json:                         "size":  124218053,
> 8. libnpp-dev-11.7.3.21-hb6476a9_0.json:                "size":  121327534,
> 9. cuda-nvvp-11.7.50-hd2289d5_0.json:                   "size":  119873153,
> 10. cuda-nsight-11.7.50-0.json:                                 "size":  119141042,
> 
> I checked the karabo_dev_env with the following command: `grep '"size":' ${CONDA_PREFIX}/conda-meta/*.json | sort -k3rn | sed 's/.*conda-meta\///g' | column -t`
> 
> Nvidia nsight for example is a GPU profiler - we have it twice in the top 10, place 1 & 10 with around 600MB in total.
