### ISSUE TITLE
Notebooks are tested (during the night?)

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#238]
The example notebooks should be tested during the night to make sure that they always work. Best would be to test them with a very up-to-date version of Karabo. Maybe we could combine this with a nightly-build of karabo? However, maybe that takes too many ressources? 

I found this on how to test notebooks with unittests: https://python.plainenglish.io/how-to-test-jupyter-notebooks-ae8e8b015d9c

**Comment by deiruch** [comment]
We should have more than enough resources to run these tests nightly.
