### ISSUE TITLE
Simulated data from SKA Data Challenge

### ISSUE THREAD

**Issue by sfiruch** [i4Ds/Karabo-Pipeline#24]
Idea by Daniel Schärer (Daniel.Schaerer@unige.ch): Use the simulations that were used for the SKA Data Challenge as well. The people organizing the challenge have probably invested a lot of time to make sure that the data is representative.

Maybe we could ask those people for the input data, re-create their instrument simulation and benchmarking?

**Comment by Lukas113** [comment]
Stale
