### ISSUE TITLE
Define how outside collaborators work with Karabo

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#244]
I first gave @jejestern write access but that did not allow her to directly work on this repo, only via a Fork and from this fork create PRs into the main project. However, after getting pinged by @jejestern, I gave her full maintain rights.

 Is that Ok @deiruch ? I think yes and I think we should add all people from the ETH-Team to this repository. Any input @Lukas113 @fschramka ?

**Comment by deiruch** [comment]
Totally agree, thanks!

("Write" access should be plenty however)

**Comment by kenfus** [comment]
It seems that with write you can only start PRs from your fork. So for someone from the ETH-Team with only write, they need to first fork Karabo, make the changes and then create a PR from their fork. They are also unable to "assign" issues to themselves. 

So, I think they should get maintain-access.
