### ISSUE TITLE
Mock MIGHTEE simulation

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#255]

**Comment by rohitcbscient** [comment]
Milestones:
1. Survey 1 - Without Primary Beam and no thermal noise
2. Survey 2 - With Primary Beam and no thermal noise
3. Survey 3 - With Primary Beam and thermal noise
https://docs.google.com/document/d/17rZjU4WEFa0QpAuZG9HqlqF8FEBLXl1RiJk50ebPY0w/edit

**Comment by kenfus** [comment]
@rohitcbscient Will upload this to a cscs-container.

**Comment by fschramka** [comment]
Will need the binary file reader started by @fschramka

**Comment by rohitcbscient** [comment]
Access the files for Survey 1 from /scratch/snx3000/rsharma/mock_mightee_0/

**Comment by rohitcbscient** [comment]
Add MIGHTEE CLEAN components into the survey - Mark's Suggestion

**Comment by deiruch** [comment]
@rohitcbscient Is this issue up to date? Do you need help?

**Comment by Lukas113** [comment]
@sfiruch do you know the status of this issue? If not I'd like to close it as stale.
