### ISSUE TITLE
User installation has standard file `pinocchio_params.conf` located in /etc/

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#256]
As we can see in the following [nightly test](https://github.com/i4Ds/Karabo-Pipeline/actions/runs/3837338196/jobs/6532525723), the user installation does not containt `pinocchio_params.conf`, used in `karabo/simulation/pinochio.py`. 

I am unsure where and how this file is installed.

**Comment by kenfus** [comment]
@fschramka Any ideas?

**Comment by fschramka** [comment]
@kenfus found a solution: wrong pinocchio was installed (https://anaconda.org/conda-forge/pinocchio) instead of the correct (https://anaconda.org/i4ds/pinocchio) - I assigned him back :)
