### ISSUE TITLE
Document Mamba in installation manual

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#283]
The installation manual does not mention mamba at all: https://i4ds.github.io/Karabo-Pipeline/installation_user.html

The `readme.md` currently only states, which is not too helpful for novice users:
> Therefore, we recommend using the libmamba solver for installation.

We need a simple, easy to follow installation description. This means:
- [ ] Explain how to install conda, set up python environments, use libmamba, all step-by-step
- [ ] Either align `readme.md` with documentation or instead link from `readme.md` to documentation

I'd expect a manual to look like:

## Initial installation
```
wget ...
bash Miniconda3-latest-Linux-x86_64.sh
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
conda create -n karabo-env python=3.9
conda activate karabo-env
conda install -c i4ds -c conda-forge -c nvidia/label/cuda-11.7.0 karabo-pipeline
```

## Update an existing installation
```
bli bla blubb
```

**Comment by deiruch** [comment]
https://docs.conda.io/en/latest/miniconda.html#linux-installers 

We should probably guide people towards a specific miniconda installation: Linux x64 with Python 3.9, no?

**Comment by deiruch** [comment]
See #287 why this is important. The current documentation apparently didn't guide André towards mamba.

**Comment by fschramka** [comment]
done in #291

**Comment by deiruch** [comment]
Hmm.. it's still inconsistent in README.MD. Can you either remove those installation sections or synchronize it with the manual?

**Comment by deiruch** [comment]
Installation in `-b`atch mode and into a certain `-p`ath (which might make sense for CSCS)
`bash Miniconda3-py39_22.11.1-1-Linux-x86_64.sh -b -p /scratch/miniconda3`
