### ISSUE TITLE
Scaling for Karabo GPU implementation

### ISSUE THREAD

**Issue by micbia** [i4Ds/Karabo-Pipeline#284]
It would be interesting to have a scaling plot for the GPU implementation of Karabo in particular for the SKA-Low setup. More precisely it would be interesting to have the computational time VS number of point sources N_pix^2 (number of pixels) and on the same plot has the scaling for observational time for t_obs = 100, 500, 750, and 1000 hours.

This would be of interest to the SDC3, so this should have the following specifications:
- Observation track length HA = -2 to +2 hours
- Integration time 10 seconds
- channel bandwidth 100 kHz
- Field of View: one SKA1-Low pointing at RA, Dec = 0h, -30deg
- Number of pixels in RA/Dec N_pix^2=2048x2048 (equivalent to the number of point sources used in the Karabo sky model)

The input can be a simple constant array (e.g: 1 mJy) with N_pix^2 pixel size, with no need for a specific mock image.

**Comment by kenfus** [comment]
Hello @micbia. I have started to set up the experiment in a notebook:

https://github.com/i4Ds/Karabo-Pipeline/blob/VT_284-scaling-for-karabo-gpu-implementation/karabo/examples/time_GPU_speed.ipynb

Does it look good from your side? of course, I would run this with different observational hours. Together with @jejestern we calculated the integration time as follows:

```
def observation_length_integration_time_to_time_steps(observation_length, integration_time):
    return int(observation_length.total_seconds() / integration_time.total_seconds())
```
Should be correct? Maybe also @rohitcbscient can have a quick look?

**Comment by micbia** [comment]
The definition you provide is correct. However, if I understand it correctly, it counts only the timesteps for one day of observation. Which, from [your script](https://github.com/i4Ds/Karabo-Pipeline/blob/VT_284-scaling-for-karabo-gpu-implementation/karabo/examples/time_GPU_speed.ipynb) is of 4 hours.

In fact, I have a question. In the new implementation of the function `ObservationLong`, the variable `number_of_time_steps` is the total number of time steps of the entire observation (from your script of 100 hours in 25 days) or for the daily observation?

If it's the latter case then the grand total number of steps should be `number_of_time_steps * number_of_days` but this is maybe calculated internally in `ObservationLong`

**Comment by kenfus** [comment]
From what I have understood here (from `observation`):

```
    :ivar number_of_time_steps: Number of time steps in the output data during the
    observation length. This corresponds to the number of correlator dumps for
    interferometer simulations, and the number of beam pattern snapshots for
    beam pattern simulations.
```

So it's for the daily observation. `ObservationLong` calls `Observation` multiple times because (i think) Oskar does not allow the horizon to go over the FOV (#134). Thus, I can adapt the function as you mentioned and then run it (of course) with different parameters.

**Comment by kenfus** [comment]
@rohitcbscient https://github.com/i4Ds/Karabo-Pipeline/blob/VT_284-scaling-for-karabo-gpu-implementation/karabo/examples/time_karabo.py

This is the script I used for timing the results I have now. Could you have a quick look at tell me if it looks overall okay?

**Comment by kenfus** [comment]
Next step: Increase it to millions of sources. -> CSCS
