### ISSUE TITLE
Karabo install failed on amazon linux

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/Karabo-Pipeline#287]
Hi everyone, I am exploring Karabo as an (yet) inexperienced user. 

Knowingly I am a mac user, so I decided to install Karabo on an amazon ec2 instance, with Amazon linux. It went quite allright, I must say. But I did run in some problems, so I thought I let you know…

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate karabo-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) [ec2-user@ip-172-31-21-150 ~]$ conda activate karabo-env
(karabo-env) [ec2-user@ip-172-31-21-150 ~]$ conda install -c i4ds -c conda-forge -c nvidia/label/cuda-11.7.0 karabo-pipeline
Collecting package metadata (current_repodata.json): | 
done
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::libstdcxx-ng==11.2.0=h1234567_1
  - defaults/linux-64::libgcc-ng==11.2.0=h1234567_1
  - defaults/linux-64::libffi==3.4.2=h6a678d5_6
  - defaults/linux-64::ncurses==6.4=h6a678d5_0
  - defaults/linux-64::openssl==1.1.1s=h7f8727e_0
  - defaults/linux-64::xz==5.2.10=h5eee18b_1
  - defaults/linux-64::zlib==1.2.13=h5eee18b_0
  - defaults/linux-64::readline==8.2=h5eee18b_0
  - defaults/linux-64::tk==8.6.12=h1ccaba5_0
  - defaults/linux-64::sqlite==3.40.1=h5082296_0
  - defaults/linux-64::python==3.9.16=h7a1cb2a_0
  - defaults/linux-64::certifi==2022.12.7=py39h06a4308_0
  - defaults/noarch::wheel==0.37.1=pyhd3eb1b0_0
  - defaults/linux-64::setuptools==65.6.3=py39h06a4308_0
  - defaults/linux-64::pip==22.3.1=py39h06a4308_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
| 
failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): | Killed
(karabo-env) [ec2-user@ip-172-31-21-150 ~]$ 
(karabo-env) [ec2-user@ip-172-31-21-150 ~]$ 
(karabo-env) [ec2-user@ip-172-31-21-150 ~]$ 
(karabo-env) [ec2-user@ip-172-31-21-150 ~]$

**Comment by kenfus** [comment]
Hello André! I am sorry that the installation caused problems. 

Stackoverflow suggests that the problem could be too little memory? -> https://stackoverflow.com/questions/64821441/collecting-package-metadata-repodata-json-killed

If that does not help, you could try to use the mamba- instead of the conda-solver, as presented in this blog-post: https://www.anaconda.com/blog/conda-is-fast-now

If that does also not fix it, I guess the problem is with amazon linux.

If you would like, we could also have a zoom call and I can try to make it work on a EC2-instance.

**Comment by deiruch** [comment]
@ACsillaghy can you tell us how much memory the VM has?

We are tracking two relevant improvements in #283 and #288.

**Comment by fschramka** [comment]
System requirements added in #291

@ACsillaghy please ensure that your VM have at least 8GB of Ram and 10GB of disk storage.

**Comment by ACsillaghy** [comment]
Hi everyone, I restarted completely with a new instance and the new installation instructions worked like a charm! I am all set now! Thank you.
