### ISSUE TITLE
System requirements are documented

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#288]
#287 documents a failed installation, most likely caused because of memory limitations. Do we know how much memory is required? We should clearly state the system requirements at the beginning of the installation manual.

**Comment by fschramka** [comment]
Requirements added in #291

Meassured Metrics:
- max Memory meassured on WSL: 6.3GB -> Recommendation went up to 8GB
- Disk Space needed during installation: 7GB -> Recommendation went to 10GB (that can be cleaned to 3.5GB afterwards)
