### ISSUE TITLE
Work around `libmpi.so.40: cannot open shared object file: No such file or directory` on ETHs euler

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#295]
PINOCCHIO doesn't work out of the box on ETHs Euler:
![image](https://user-images.githubusercontent.com/4119188/216648025-51c0dbd1-b36a-409d-9855-ddfc105170d4.png)

Potential workarounds:
- Invoke ETHs proprietary `load library` script
- Install a more specific openmpi version (perhaps openmpi=4.1.4=ha1ae619_100, see https://github.com/theislab/cellrank/issues/864)

**Comment by fschramka** [comment]
Fixed in the latest pinocchio release - just reinstall pinocchio to solve the problem.
