### ISSUE TITLE
Clarify documentation when to call `setup_jupyter_env()`

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/Karabo-Pipeline#297]
When starting the docker image as explained
docker run -p 8888:8888 -v ska_pipeline_code:/home/jovyan/work/persistent ghcr.io/i4ds/karabo-pipeline:jupyter
it works well. 
However, the next paragraph is unclear: 

_"Choose the Karabo Kernel to run your Karabo pipeline. Also use the function setup_jupyter_env() at the start of your .ipynb file. It sets a crucial environment variable for our imaging. This is only needed when running karabo in a jupyter environment. When running the pipeline from the Command line this variable is already set."_

I chose the karabo image, but I then I am stuck:

<img width="1216" alt="Screenshot 2023-02-04 at 07 40 30" src="https://user-images.githubusercontent.com/18006843/216753141-a82dc8a2-7595-4b10-add4-504464a854f3.png">

What did I miss? I just followed the documentation.

**Comment by deiruch** [comment]
@kenfus Is this even necessary anymore? We set the RASCIL data directory automatically anyway in `__init__.py`? If not, can't we make sure it's called before using RASCIL for the first time?

Or is this a doc fix?

**Comment by kenfus** [comment]
Updated the doc.
