### ISSUE TITLE
Docker image contains prepared Jupyter notebook

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/Karabo-Pipeline#298]
It would be nice to have in the docker image a prepared notebook with the instructions given in the documentation. "untitled.ipynb" is not facilitating the starting and even confusing as it gives the impression that I am not in the correct path

**Comment by Lukas113** [comment]
As soon as PR #348 is accepted, future Docker release images contain the in `karabo/examples/` containing Jupyter Notebooks in the `/workspace/examples/` directory of the according release-checkout.
