### ISSUE TITLE
The beam_method "KatBeam" in simulate beam raises a NameError when called

### ISSUE THREAD

**Issue by jejestern** [i4Ds/Karabo-Pipeline#301]
I tried to do a primary beam simulation like it is shown in the function test_beam in test_beam.py, but I used "KatBeam" as a beam_method. I get the following error
![Bildschirmfoto vom 2023-02-06 18-34-31](https://user-images.githubusercontent.com/43879522/217044368-15b4a815-dbf6-400a-bff1-b99eabd07cde.png)
I think one needs to add a self. when calling get_meerkat_uhfbeam. 
After I did this I got a new error message:
![Bildschirmfoto vom 2023-02-06 18-33-57](https://user-images.githubusercontent.com/43879522/217044755-1e507e45-1088-478d-a219-a2ff0c078fee.png)
What is f? I guess one needs to choose a value for f.

**Comment by kenfus** [comment]
Yes, I see it's a bit broken. It needs to be `BeamPattern.get_meerkat_uhfbeam(..)` but I am unsure what f is supposed to be:

![image](https://user-images.githubusercontent.com/47979198/217196318-66b2d98f-cf0e-4d07-b3b9-ffc4d50c1bad.png)

It seems that f is some sort of frequency?

**Comment by deiruch** [comment]
@rohitcbscient can you help?
