### ISSUE TITLE
PINOCCHIO: Avoid 'PLC count overshooted' error

### ISSUE THREAD

**Issue by PascalHitz** [i4Ds/Karabo-Pipeline#302]
In pinocchio the tasks accumulate halos that are written to the past lightcone file. Once all tasks have reached a certain redshift, the halos are written to the disk and the memory is reset. With pinocchio 4.1.3, we had the problem that if there were many box replications from which the halos are accumulated, the memory might be saturated before the output redshift is reached. Thus, some halos will be missing in the lightcone file, resulting in the error warning _PLC count overshooted_ in our job.

<img width="467" alt="Bildschirm­foto 2023-02-07 um 09 25 33" src="https://user-images.githubusercontent.com/102365411/217250782-fa1df699-44ae-488f-857b-cc05907c0426.png">

To avoid this problem, we can increase the frequency with which we write the accumulated halos to the disk by increasing the _DeltaF_PLC_ parameter in _build_groups.c_ line 123.

So far we did this hard-coded by setting _DeltaF_PLC_ = 0.98 instead of 0.9 for our half-sky pinocchio run from redshift 0.77-1.03, but it would also be nice to include this parameter as an additional choice in the parameter file, e.g. such that it is set to 0.9 by default but the user could change it.

**Comment by PascalHitz** [comment]
Here are the parameter and outputs file for the run.
[pinocchio_params.conf.txt](https://github.com/i4Ds/Karabo-Pipeline/files/10825112/pinocchio_params.conf.txt)
[outputs.txt](https://github.com/i4Ds/Karabo-Pipeline/files/10825114/outputs.txt)

**Comment by fschramka** [comment]
DeltaF_PLC can now be given as a parameter through the parameter file. 

Pinocchio is installable like always via conda:
`conda install -c i4ds -c conda-forge pinocchio`

Here is the new layout of the parameter file: 
[pinocchio_params.txt](https://github.com/i4Ds/Karabo-Pipeline/files/10827283/pinocchio_params.txt)

This is the default file for pinocchio which uses the test inputs from the author and can be found after the conda installation under:
~/miniconda3/envs/CONDA_ENV_NAME/etc/pinocchio_params.conf
