### ISSUE TITLE
Update tests 

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#306]
- [ ] check test coverage
- [ ] replace commenting out tests with @unittest.skipIf( `some environment variable`) (see `test_notebooks.py`)
- [ ] update tests if possible with output checking

Also, because for some reason the test report is now failing (see https://github.com/i4Ds/Karabo-Pipeline/actions/runs/4123638884), I would switch to pytest, which is more widespread, generates a cleaner report and is overall more readable. In addition, I was also unable to make tests locally work with unittest but it worked instantly with pytest (which is compatible to unittest).

**Comment by fschramka** [comment]
Some tests are dependend on each other. There is functionallity in pytest tp check this. Currently some tests fail because other tests did not create some files...

**Comment by deiruch** [comment]
@kenfus Should this issue be closed? (Note: I'll create another one about test coverage)
