### ISSUE TITLE
Make final karabo images consistent in grid resolution with the neutral fraction simulation images (128^2*500). These would be used to create differential brightness.  The data challenge cubes are bigger (~2000).

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#319]
@rohitcbscient Does this mean pixel size of 128x128 with 500 channels?

**Comment by kenfus** [comment]
So from what I've seen in the `Image` Class the `plot` function takes the first channel with `self.data[0]`. If we pass to `Observation` 64 channels and to `Imager` `imaging_npixel of 2048`, we get `self.data.shape == (64, 1, 2048, 2048)`. It seems that everything is already implemented, we just have to implement `differential brightness`. Is that the differenent brightness per channel or per source?  Here is the input of chatgpt:

```
Differential brightness refers to the difference in brightness or luminance between two objects or regions in an image. It is often used in image processing and computer vision applications to identify features or changes in an image.

For example, in medical imaging, differential brightness can be used to detect changes in tissue density or contrast between different organs or structures. In astronomy, it can be used to identify variations in the brightness of stars or galaxies.

The term "differential" is used because the brightness difference is typically calculated by subtracting the pixel values of one region from another, or by taking the ratio of the pixel values between two regions.

Differential brightness can also refer to the difference in brightness or intensity between different channels or wavelengths in interferometry. In interferometry, different channels or wavelengths are often used to capture different aspects of the signal, such as spatial information or spectral content.

By analyzing the differential brightness between different channels, interferometry can be used to extract information about the structure and properties of the source of the signal, such as the size, shape, and composition of astronomical objects like stars and planets.

In this context, differential brightness is often used in combination with other techniques, such as Fourier analysis, to extract detailed information from interferometric data.
```

**Comment by deiruch** [comment]
@kenfus Maybe talk to Michele directly?

**Comment by kenfus** [comment]
@micbia Could you please explain “differential brightness” either to me or make sure that @rohitcbscient understands, so that I can implement it. Or do you have any good papers explaining the concept? Thank you!

**Comment by kenfus** [comment]
- [ ] Implemented new function which reads in the fits file `block_visibilities = create_blockvisibility_from_ms(self.visibility.file.path)` and samples it to the requested shape.
- [ ] Scipy interpolation `bivariateSpline` as Standard
- [ ] Good standard settings, can be overwritten
