### ISSUE TITLE
`Pinocchio.getSkyModelFromFiles` is either disabled or correctly translates masses into fluxes

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#325]
Currently, it works like this:

```
skyModArr[i, Pinocchio.PIN_RIGHT_ASCENSION_IDX] = ra
skyModArr[i, Pinocchio.PIN_DECLINATION_IDX] = dec
skyModArr[i, Pinocchio.PIN_I_FLUS_IDX] = 1
skyModArr[i, Pinocchio.PIN_Q_FLUS_IDX] = 0
skyModArr[i, Pinocchio.PIN_U_FLUS_IDX] = 0
skyModArr[i, Pinocchio.PIN_V_FLUS_IDX] = 0
skyModArr[i, Pinocchio.PIN_REF_F_IDX] = 1.0e8
```

However, there is no translation of mass into flux happening, which is depended on the mass found around the dark matter.

@jejestern said that this is probably too hard to implemented because it's dependent on the elements the user wants to analyze. So she suggests testing the output from Pinocchio directly (e.g., mass distribution, ...) without a `SkyModel` in between.

**Comment by jejestern** [comment]
The following script by Pascal Hitz which I adapted a little, converts the output of Pinocchio to flux generated by 21cm of neutral hydrogen. The flux is saved together with position and redshift information into a h5 file. This cataolg can be then used to create a sky model, the way I do it in karabo/examples/HIIM_Img_Recovery.ipynb (not included in the main branch yet).
[flux_calculation1_Battye.zip](https://github.com/i4Ds/Karabo-Pipeline/files/10826406/flux_calculation1_Battye.zip)
