### ISSUE TITLE
Implement Ionospheric Screen into Karabo

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#326]
Oskar has an implementation for inserting time-varying ionospheric screen based on ARastmospy (https://github.com/shrieks/ARatmospy)
Oskar Doc: https://ska-telescope.gitlab.io/sim/oskar/python/example_ionosphere.html?highlight=ionospheric%20screen

**Comment by chrisfinlay** [comment]
We would like to include this into the SDC3a simulations. What is required to get this working? Can we edit the OSKAR settings tree directly to include 'telescope/external_tec_screen/input_fits_file'?

**Comment by deiruch** [comment]
Unit test is failing, will try to merge soon.
