### ISSUE TITLE
pre-commit-hooks prevents the upload of .ipynb scripts

### ISSUE THREAD

**Issue by jejestern** [i4Ds/Karabo-Pipeline#330]
When using the pre-commit-hooks it is not possible to commit/push any .ipynb scripts due to the fact that flake8 does not support them. I now used the --no-verify flag in the git-commands. Maybe it would be a good idea to exclude the .ipynb scripts from the pre-commit-hooks (if possible) or include flake8-nb which is the equivalent for jupyter notebooks. @Lukas113 What do you think?

**Comment by Lukas113** [comment]
@jejestern Hmm, I tried to reproduce your issue with existing notebooks (also HIIM_Img_Recovery.ipynb) on the latest commit of `JS_301-the-beam_method-katbeam-in-simulate-beam-raises-a-nameerror-when-called` and I didn't encounter any problems. Can you push the notebook which is causing the issue to your branch? Then I should be able to reproduce it and have look for a solution.

To answer your question, I think jupyter notebooks should be included for the formatting checks if possible. Of coure it should be easly managable. My pre-commit output to a dummy commit with obvious flake8 violations in `HIIM_Img_Recovery.ipynb` was :

![image](https://user-images.githubusercontent.com/32157249/220934032-b1a9aeba-7652-44d6-ab93-fd684e93bc4d.png)

So therefore I don't think that the pre-commits are checking the notebooks. I also didn't see any configuration therefore in the`setup.cfg` file.

**Comment by Lukas113** [comment]
Yeah I think including [flake8-nb](https://pypi.org/project/flake8-nb/) makes sense. I will test it out tomorrow.

**Comment by jejestern** [comment]
@Lukas113  The notebook which was causing the problem is HIIM_Img_Recovery.ipynb. I had to use the --no-verify flag i order to commit. The problems occur if you change something in the markdowns.

**Comment by jejestern** [comment]
@Lukas113 The commit with which I had problems was in the JS_301-the-beam_method-katbeam-in-simulate-beam-raises-a-nameerror-when-called branch. The commit I did on the 22.02.2023 at 10:45. Maybe the reason why I was not able to commit was the h5 file, since the file has a size of 7.2MB.

**Comment by Lukas113** [comment]
Ok, I will have a look at it.

**Comment by Lukas113** [comment]
@jejestern I have changed some markdown, rerun some output and violated other flake8 conventions in the code. However, I'm still not able to reproduce your issue. To me it seems that the pre-commit hooks completely ignore the jupyter notebooks on my machine. I've also set up a new virtual-environment with a fresh karabo_dev_env installation and installed the formatters and hooks again, but nothing changed.

Can you provide me with the exact error you've got? At best, a screenshot of the pre-commit hook output. 

In the meantime, I'll look how to integrate flake8 and isort checks for jupyter notebooks.

**Comment by Lukas113** [comment]
If the error output was only related to the .h5 file then it is not a jupyter notebook issue. This was the only error I was able to get by running/changing the notebook (see figure below). In `.pre-commit-config.yaml` there is a `check for added large files` hook which prevents large files to be commited (which is desired since we don't use `git-lfs` for our repository as far as I'm aware).

![image](https://user-images.githubusercontent.com/32157249/221175804-74715ac5-3708-4607-936e-2712cfead259.png)

**Comment by Lukas113** [comment]
I've investigated a little bit and played with `flake8-nb`. It seems to work if you install it and use `flake8-nb .` instead of the usual flake8 command. However, it downgrades flake8 from 6.0.0 to 5.2 which is a major downgrade and therefore I don't really like it. I think it is sufficient to just run `black` through the jupyter notebooks and look out for obvious flake8 violations if we see any.

**Comment by jejestern** [comment]
@Lukas113  
Yes, I think the problem was just the large file and not the jupyter-notebook. Sorry for that. I also do not plan to leave the h5 file on the github branch. We just need it for testing the primary beam.

**Comment by jejestern** [comment]
Okay. Thank you for clarifying @Lukas113.

**Comment by Lukas113** [comment]
@jejestern always happy to help. 

If you have large files that doesn't belong to the Karabo repository, using something like `scp` would be appreciated. The main reason is even if you remove the h5 file with another commit, it still remains in the git history if we don't remove the commit by e.g. deleting the branch afterwards.
