### ISSUE TITLE
`from casacore.tables import table` does not fail with `ImportError: libfftw3f_threads.so.3: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#338]
It seems that casacore has forgot to add a dependency:

https://github.com/i4Ds/Karabo-Pipeline/actions/runs/4280803718/jobs/7453072817

The same tests also fails locally for me on a new `dev-env`.

**Comment by fschramka** [comment]
related to wrong fftw import - will be fixed with the rel_v14 dep tree

**Comment by Lukas113** [comment]
The test succeeded in the [workflow](https://github.com/i4Ds/Karabo-Pipeline/actions/runs/4423869534) on the branch `LG_298_docker` .

**Comment by Lukas113** [comment]
@kenfus is it solved since the release `v0.15.0`? If yes, we could close this issue.
