### ISSUE TITLE
Encapsulate current usage of RASCIL into a karabo module

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#34]
Add a new module named Imaging and define interfaces for imaging, with rascil as an implementation.
Hide dask features and other implementation details in our implemantion.

**Comment by Lukas113** [comment]
I've made an imaging module which just encapsulates the imaging process without the usage of CLI. The variable names and the default values of the variables are according to the RASCIL initializations. This is done in the branch object_detection.
