### ISSUE TITLE
no gpu brings an error in the simulation example (but it does run) 

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/Karabo-Pipeline#350]
This is on my new EC2 instance:

observation = Observation(start_frequency_hz=1e6)

No GPU is available
use_gpu is None, using is_cuda_available() to set use_gpu to False
No GPU is available

/bin/sh: nvidia-smi: command not found
/bin/sh: nvidia-smi: command not found

**Comment by kenfus** [comment]
That is expected but I agree that the error message could be much better. Basically, `is_cuda_available()` is a function by karabo which checks if the system has a GPU available with CUDA support and if it does, uses the GPU-acceleration wherever applicable.
