### ISSUE TITLE
Exploring W&B for experiment tracking

### ISSUE THREAD

**Issue by ACsillaghy** [i4Ds/Karabo-Pipeline#352]
The potential of Karabo is also in its possibility of tracking experiments with different parameters at all levels. I think W&B could be "misused" for this. It would provide a nice user interface and would spare us a lot of efforts. 
https://wandb.ai/site/solutions/scientific-research
Should we evaluate the feasability?

**Comment by deiruch** [comment]
Will close until we have concrete use cases. @ACsillaghy feel free to reopen.
