### ISSUE TITLE
TEST_FORMATTING does not fail with `Error: Docker login for 'ghcr.io' failed with exit code 1`

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#353]
https://github.com/i4Ds/Karabo-Pipeline/actions/runs/4403177365/jobs/7711217264

**Comment by Lukas113** [comment]
@kenfus I don't see why this is an issue. I've just seen it fail once and if so, then there is nothing I can do about that.

**Comment by kenfus** [comment]
Ah ok, so it's just an error which happens sometimes with docker images?

**Comment by Lukas113** [comment]
I saw this issue for the first time. I'm not sure whether this is a registry, or a github workflow issue. But there is nothing to do about that as long as our tests rely on docker.
