### ISSUE TITLE
remove conda label "old" from karabo-releases

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#359]
I've seen that our legacy karabo [conda builds](https://anaconda.org/i4Ds/karabo-pipeline/files) are tagged with the `old` label. I don't really see the reason why we do that. As far as I know most package-provider leave their builds with the `main` label and the legacy builds are referenced just by version. But since we have a `rel_v*` channel setup for karabo dependencies, I think we should adapt to that setup.

The required changes are:

- [x] Relabel existing build from `old` to `rel_v*` setup
- [x] Change Setup in GitHub Workflow(s)
- [x] Change Setup in Dockerfile.user
- [x] Adapt documentation
- [x] Look if other changes are necessary

**Comment by Lukas113** [comment]
Hmm, I think since we do the label-management for the other packages with `rel_v*` I think the karabo-labels should also follow the according setup. This seems more consistent and would reduce the number of channels to reference in `conda install` by 1.

**Comment by fschramka** [comment]
Exactly :) do it!

**Comment by Lukas113** [comment]
I've done the changes in PR #348 . What remains is the relabeling or removal of legacy karabo conda builds. As soon as the release is done, I will take care of that. I prefer the removal of legacy karabo builds < v0.15.0 because they don't work (can't even install because `bdsf` dependency is missing).

**Comment by Lukas113** [comment]
Everything is done according to the setup mentioned in #373 (not setup depicted above). I wasn't sure whether to remove karabo < 0.15.0 or not because the package can't be installed. For the moment, I relabeled from `old` to `main`.
