### ISSUE TITLE
Parameters to functions and classes are passed when they are needed.

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#363]
Example: `ingest_vis_nchan` is needed only in `imaging_rascil` but it's passed to the `init` of `Imager`.

**Comment by deiruch** [comment]
@kenfus Can you convert this into an actionable TODO-List of places where we should change this?

**Comment by Lukas113** [comment]
Closed, because there there was no further elaboration or activity in this issue.

**Comment by deiruch** [comment]
@kenfus Agree?
