### ISSUE TITLE
Test Noise Implementation of OSKAR

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#40]
- [ ] benchmark
- [ ] add interface if the benchmark is successful

**Comment by deiruch** [comment]
Duplicate of #23

**Comment by cvoegele** [comment]
https://ska-telescope.gitlab.io/sim/oskar/settings/settings-interferometer.html?highlight=noise#interferometer-noise-seed

**Comment by deiruch** [comment]
@rohitcbscient Tested this on oskar & already wrote unit tests. Noise is solely uniform RMS noise.

**Comment by rohitcbscient** [comment]
I have created a pull request for the same. The system noise is implemented in accordance with Oskar.
