### ISSUE TITLE
Add SKA LOW and SKA Mid Telescope Configurations

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#42]
Create new functions in the telescope.py to, so the users can get the SKA Low and SKA mid telescope configurations with a single function call.

**Comment by deiruch** [comment]
More info:
https://www.skatelescope.org/key-documents/ 
https://astronomers.skatelescope.org/swg-chairs-meeting-minutes/ (Perhaps January 2022 meeting?)

@rohitcbscient knows more

**Comment by rohitcbscient** [comment]
The configuration for SKA-low and SKA-mid is also added.
