### ISSUE TITLE
Design a good 95%-OSKAR-compatible-API for RASCIL

### ISSUE THREAD

**Issue by sfiruch** [i4Ds/Karabo-Pipeline#421]
Design a good 95%-OSKAR-compatible-API for RASCIL

_Originally posted by @deiruch in https://github.com/i4Ds/Karabo-Pipeline/issues/415#issuecomment-1563999299_

**Comment by lmachadopolettivalle** [comment]
Current design approach:

(In the following, "framework" refers to the backends, e.g. OSKAR and RASCIL.

- [ ] Every resource class will store a framework agnostic dataset. E.g. `Observation` will store a series of floating point values for the configurations, `SkyModel` will store a DataFrame with columns corresponding to sky source properties, etc.
- [ ] Every resource class has methods to convert its data into objects compatible with any given framework. E.g. convert the DataFrame from `SkyModel` into a OSKAR-specific `array`, or a RASCIL-specific list of `skycomponents`

The resource classes that need to be reviewed and (if needed) modified are:
  - [ ] Observation
  - [ ] Telescope
  - [ ] SkyModel
  - [ ] Interferometer
  - [ ] Visibility
  - [ ] Image
