### ISSUE TITLE
Include coadd class/function 

### ISSUE THREAD

**Issue by jejestern** [i4Ds/Karabo-Pipeline#424]
we use montagepy

**Comment by Lukas113** [comment]
Thanks. I think I'll have a look at this next week.

**Comment by Lukas113** [comment]
MontagePy is build through [Karabo-Feedstock](https://github.com/i4Ds/Karabo-Feedstock/tree/main/.github/workflows) and available at [anaconda](https://anaconda.org/i4ds/montagepy). The [Montage](https://github.com/Caltech-IPAC/Montage) build version is v6.0 which was build from [MontagePy pypi wheels](https://pypi.org/project/MontagePy/#files) for Python 3.9 and 3.10.

The conda build is not tested yet, that's work in progress.

**Comment by Lukas113** [comment]
The conda-build is tested and seems to work fine. The wheel URL reference to pypi is a hard reference which could change at some point in time. But I'm not sure on how to fix that quickly in a properly and it doesn't seem to be urgent.
