### ISSUE TITLE
Comparison of Karabo and the Hirax/Devin's Pipeline

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#43]
- No noise, no RFI
- Trivial sky model
- Are the results similar?

**Comment by deiruch** [comment]
HD Pipeline only supports bitmaps, we only support point sources. Next, we can use point sources - or several from GLEAM. Goal is to confirm a rough correspondence between the two pipeline results.

**Comment by rohitcbscient** [comment]
The benchmark run is successfully tested to generate the same visibilities between HIRAX and karabo pipelines. The benchmark run consisted of stimulating point source on Zenith using MeerKat configuration.
