### ISSUE TITLE
Imager works without users explicitly calling `visibility.write_to_file` before

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#438]
In [karabo/test/test_ionosphere.py](https://github.com/i4Ds/Karabo-Pipeline/pull/418/files/93d029e70d9db6837781b66ec44249acdf015190#diff-94a4477112ce41a1aa7551f48c4027b1e4851d257f4663e440ffe4b62b41a7c7) there's the following code:
```
        visibility = simulation.run_simulation(telescope, sky, observation)
        visibility.write_to_file("./result/test_ion.ms")
```

According to @Lukas113 the explicit writing of visibilities to a file is because the Imager requires that a .ms path exists.

Users shouldn't be required to trigger this file write explicity, for a variety of reasons:

- The correct file format depends on the imager (e.g. it might be dask-ms)
- Users might not be interested in intermediate data products
- Users might forget to call this explicit write

For this reason, the imager code should trigger required writes when they are necessary, in the preferred format, automatically.

**Comment by kenfus** [comment]
The user is not required anymore to do this. The path to the ms file can be accessed as follows:

`visibility.ms_file.path`

**Comment by Lukas113** [comment]
I overlooked something there. It is correct that the Imager requires that Visibility has an .ms path. However, it is set in run_simulation and therefore it is not needed to be written explicitly. Therefore, I think we can close this issue.
