### ISSUE TITLE
Make pybdsf work with numpy >1.22

### ISSUE THREAD

**Issue by fschramka** [i4Ds/Karabo-Pipeline#449]
HVOX needs Numpy >=1.23 (Mentioned by @Lukas113 in #426), our current feedstock is restricted to numpy=1.22 due to restrictions in pybdsf (https://github.com/lofar-astron/PyBDSF). 

In
https://github.com/lofar-astron/PyBDSF/blob/master/pyproject.toml
are the following dependencies:
- oldest-supported-numpy
- setuptools<65.6

This blocks newer numpy versions. We need to make this work in order to add new dependencies such as HVOX.

**Comment by deiruch** [comment]
Context here: https://github.com/lofar-astron/PyBDSF/issues/202#issuecomment-1629757714
