### ISSUE TITLE
Oskar raises warning when any beam other than gaussian is passed

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#463]
- Oskar does not support any beams other than gaussian

**Comment by jejestern** [comment]
Oskar does not support custom beams, but you can choose between four beam types (see telescope/station_type at https://ska-telescope.gitlab.io/sim/oskar/settings/settings-telescope.html) which are given by Oskar.

**Comment by deiruch** [comment]
This should also be mentioned in the documentation. Can you add a sentence or two?
