### ISSUE TITLE
Support multiple ALMA configuration cycles

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#47]
[Omkar Bait](https://app.slack.com/team/U02P4R19MPV) [Today at 3:58 PM](https://swissska.slack.com/archives/C02M54N7WDR/p1645801126247629)
Hi All. Is it possible to change the ALMA telescope configuration depending on the ALMA cycle id in the current pipeline?

4 replies

[Rohit Sharma](https://app.slack.com/team/U01GCD07TLH)  [1 hour ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645801198580049?thread_ts=1645801126.247629&cid=C02M54N7WDR)
Yes, definitely. Just point me to the link of the configurations.

[Omkar Bait](https://app.slack.com/team/U02P4R19MPV)  [45 minutes ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645801361027619?thread_ts=1645801126.247629&cid=C02M54N7WDR)
Thanks. This link has all the configurations upto Cycle 8: https://almascience.eso.org/tools/casa-simulator

[Mark Sargent](https://app.slack.com/team/U02P5R6V0TC)  [44 minutes ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645801389224379?thread_ts=1645801126.247629&cid=C02M54N7WDR)
Note, however, that within a given cycle various configurations are used.

[Omkar Bait](https://app.slack.com/team/U02P4R19MPV)  [42 minutes ago](https://swissska.slack.com/archives/C02M54N7WDR/p1645801527824399?thread_ts=1645801126.247629&cid=C02M54N7WDR)
Yes, the configuration file is tagged as cycle_number.x, index x denotes different configurations within a cycle. I guess this can be used as an input parameter.

**Comment by cvoegele** [comment]
Keep naming of configurations, and add all 25 configurations

**Comment by rohitcbscient** [comment]
Added in the data folder.
