### ISSUE TITLE
Prepare first data set

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#5]
The pipeline should come with a set of test data. Could be simulated, real-world data, or both.

For #8 we'd like to have realistic, real-world data sets and simple, synthetic tests.

**Comment by Lukas113** [comment]
Currently besides of the SARAO archive I haven't found easy accessible real datasets which everyone has access to.

What I have found is a little 1.2GB calibrated measurement set observed by VLA of a supernova remnant accessible through https://casaguides.nrao.edu/index.php/VLA_CASA_Imaging-CASA4.6.0.

**Comment by Lukas113** [comment]
In addition, @rohitcbscient has downloaded some observations in the .fits format of "Cygnus A" & "Centaurus A" from:

https://ned.ipac.caltech.edu/byname?objname=Cygnus+A&hconst=67.8&omegam=0.308&omegav=0.692&wmap=4&corr_z=1

We should be able to put them into Oskar somehow at some point

**Comment by deiruch** [comment]
Here's a (quick) way to create synthetic data sets, suggested by Michele Bianco: https://21cmfast.readthedocs.io/en/latest/. They are using it already, successfully.

**Comment by deiruch** [comment]
@Lukas113 is bundling a small part of the GLEAM survey for #20
