### ISSUE TITLE
conda-build.yml does not use an old docker image anymore

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#507]
https://github.com/i4Ds/Karabo-Pipeline/blob/main/.github/workflows/conda-build.yml is currently using a very old docker image with mamba preinstalled. However, when updating the file to use an action with preinstalled conda, the building process cashes with OOM errors.

Updated file: https://github.com/i4Ds/Karabo-Pipeline/blob/84a3663110037c7ed2aed63f0711a4ebff90a566/.github/workflows/conda-build.yml

Failed runs (Example): https://github.com/i4Ds/Karabo-Pipeline/actions/runs/5857833721/job/15880559176

When this is fixed, the user package can also be readded in this script and run before the package is uploaded to anaconda.

**Comment by deiruch** [comment]
@Lukas113 Is this still an issue?

**Comment by Lukas113** [comment]
no, it's not an issue anymore. closed
