### ISSUE TITLE
Notesbooks can be tested with the built package of karabo

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#509]
Currently, when testing the notebooks on the installed package, the pytest is killed. This happens also locally for me. I don't know why. 

Example on a GitHub runner: https://github.com/i4Ds/Karabo-Pipeline/actions/runs/5858833188/job/15884912205

The notebooks are tested nightly on the GitHub checkout, so that should be ok. 

Thus, the notebooks are not tested on the user installation (package).

**Comment by Lukas113** [comment]
@kenfus no logs available anymore. However, I think this issue is the same as #531 I think? If yes, please close this issue. If it's not the same, I think you should elaborate more on this issue.
