### ISSUE TITLE
Fix CUDA builds for OSKAR.

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#51]
The Linux builds for OSKAR with Cuda are working, but when they are then imported on a host machine. The linker cannot find the cuda runtime libraries.
Investigate why the libraries cannot be found on the host even if the cudatoolkit is added as a dependency for conda.
If the libraries are found it should be possible to run the OSKAR version with CUDA on non-cuda enabled devices. As the OSKAR implementation always checkes if CUDA devices are actually present.

For now the OSKAR conda packages are working but only with CPU computing, which is a bit slower.

**Comment by deiruch** [comment]
@fschramka Do you know whether CUDA works on CSCS?

**Comment by deiruch** [comment]
@kenfus  I think this is fixed now, no?

**Comment by deiruch** [comment]
Fixed according to @kenfus
