### ISSUE TITLE
Integrate FARM (Foreground All-scale Radio Modeller) into Karabo

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#518]
https://github.com/SimonP2207/farm
Design tests for the cosmology science cases using farm.

**Comment by rohitcbscient** [comment]
Consult Michele for implementing this.

**Comment by deiruch** [comment]
@rohitcbscient What's the priority? Do you have a specific use-case in mind?

**Comment by rohitcbscient** [comment]
I think this is for the EoR case. We also did not base our SKADC analysis on this, so we can reopen if there are use cases for it.
