### ISSUE TITLE
Add data sets from Olga Taran

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#52]
From Olga Taran (Olga.Taran@unige.ch):
> [...] we expect to have the first simulated data (about 1 thousand) next week.
> With respect to the ms files I am not sure because they are quite heavy and in this case we need to find the proper storage 
since you can not have direct access to our servers due to the University rules and it might take some time.
> At the same time, the true sky model, the dirty and clean images we will share with you via one of our clouds since they are less heavy. The produced images will be of size 512 x 512 pixels and the sources will be of different intensity and shape.

**Comment by rohitcbscient** [comment]
The software needed for the task is DeepClean.
https://github.com/wmorning/DeepClean

**Comment by deiruch** [comment]
Apparently, they are unable to share the data & scripts at this time.
