### ISSUE TITLE
Publicly runnable example notebook exists

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#556]
If we upgrade to Python 3.10 #519, we could create easily (probably) a notebook, hosted on google colab, which can be run by anyone easily.

Steps:

- Create a google colab notebook
- Install https://github.com/conda-incubator/condacolab
- Install Karabo
- Upload an example notebook, such as source detection
- Check that it all works.

**Comment by sfiruch** [comment]
Instead of Google Colab, we could use Renku instead?

**Comment by anawas** [comment]
Yes, we can. I will set up a demo notebook. However, computing capabilities are limited on Renku. But it'll be fine as playground to demonstrate Karabo.

**Comment by anawas** [comment]
We can close this issue. There is an example notebook on Renkulab: https://renkulab.io/projects/menkalinan56/swissskadays-karabo-workshop
I wrote this for the workshop at Swiss SKA days. It comes with a slide deck as wel.

**Comment by mpluess** [comment]
Nice! Is this linked somewhere so interested people can find it? If not, maybe add it to https://github.com/i4Ds/Karabo-Pipeline/blob/main/README.md or https://i4ds.github.io/Karabo-Pipeline/examples/examples.html?
