### ISSUE TITLE
Reverse RA axis on images from sky model

### ISSUE THREAD

**Issue by anawas** [i4Ds/Karabo-Pipeline#574]
The RA axis on images from sky model simulation run from left to right (lower values on left hand side). On images from the observation simulation the axis runs from right to left. This seems to be the common case for all astronomical images.

We should swap the direction in the plotting function from `SkyModel`. Maybe adding a flag which allows the user to choose the direction?

**Comment by Lukas113** [comment]
Resolved: when `xlim` values are reversed, so will the RA-axis.
