### ISSUE TITLE
Generated telescope.tm as tmp does not work

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#59]
I've seen that the temporary construction of a telescope.tm file and set it in the OSKAR simulation (simulation.set_telescope_model in interferometer.py) leads to incorrect visibilities (I've not seen any sources in the produces image from this visibilities). However, when I take the same constructed telescope.tm file and refer to it in the setting tree I got the correct visibilities. Therefore, I made a hotfix where I just refer to the telescope.tm file in the data folder.

**Comment by Lukas113** [comment]
Somehow I thought that initializing the telescope correctly has solved the issue but it has not. So I've made a commit (53905ce7c4b1e1e40a60cf5ebe8f22b50fe3a079) for a hotfix on the object_detection branch since I need this to run the pipeline. But now all it does is take the .tm file if one is set and available in the /data directory.

**Comment by rohitcbscient** [comment]
Initialising the telescope either way works on my PC.
