### ISSUE TITLE
Casa MS file path args should support Visibility class

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#616]
This issue originates from PR #612 where we had a discussion about whether `ImageCleaner.create_cleaned_image` should be a `Visibility` object or not. Lookup on discussion details can be looked up in the PR.

The TLDR is make visibility args positonal-only and accept casa MS and `Visibility`. This is an API breaking change.

**Comment by mpluess** [comment]
Assigned myself since I wanted to address this anyway in #595
