### ISSUE TITLE
imaging with bigger cellsize

### ISSUE THREAD

**Issue by Lukas113** [i4Ds/Karabo-Pipeline#64]
During my tests with source detection, I noticed that when I wanted a larger image, the sources disappeared. I did this with a filtering of the GLEAM survey with ra=250 dec=-80 and a filtering of radius 0.55 degree from the phase center. The imaging parameters were 2048 pixels and a cellsize of 1.1079e-5 (1.1079e-5*2048*180/pi = 1.3 degree, which should completely cover the 1.1 degree from the filtering). However, when I used a cellsize of 3.8785e-5 (about 4.5 degrees), the sources were present at the calculated locations as expected. If I took a cellsize of 1.70044231e-5 (ca 2 degree) the sources were at the expected locations, but they had an interesting pattern (major axis FWHM, minor axis FWHM and position angle were also provided).

This was only the result of a few tests, i.e. it was not tested extensively. Therefore it is worthwhile to reproduce this and find out what the reason is. My guess is that I did not understand all the imaging parameters and therefore did not set them correctly.

**Comment by deiruch** [comment]
Not a bug, according to @rohitcbscient
