### ISSUE TITLE
Bundle Pinocchio with Karabo 

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#65]
Integrate https://github.com/pigimonaco/Pinocchio into Karabo. @PascalHitz knows the Pinocchio Code and how to use it.

Goals:
- [x] #89
- [x] CI build, packaging, deployment
- [x] #91
- [x] #90
- [x] #101
- [x] #102

**Comment by deiruch** [comment]
Apparently we should use the current GH version 4.1.3 (instead of 4.1.2, which is published on the website).

**Comment by PascalHitz** [comment]
Here are the parameter and output file of my run. I already changed the output file such that it includes redshift 1.0 and 0.0.
[parameter_output_file.zip](https://github.com/i4Ds/Karabo-Pipeline/files/8688544/parameter_output_file.zip)

**Comment by fschramka** [comment]
I guess you did not want to close this one?

**Comment by PascalHitz** [comment]
Sorry, accidentally pressed the wrong button!

**Comment by fschramka** [comment]
it is bundled now - but the conda environment cant be created on macos - will further investigate this.
