### ISSUE TITLE
Identify CSCS execution models

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#7]
We should get answers to these questions:
- [x] Can we develop remotely on CSCS?
- [x] Can we mix local/remote running? I.e. develop locally, and run computationally intensive parts on CSCS?
- [x] (How) can we let the public use CSCS infra?
- [x] Should we use containers/Docker or not?
- [ ] How should we deal with Big Data? What are our options? Do we co-locate computation with data?

We should come up with a (written-down) vision how we could/should use the CSCS infra.

**Comment by Lukas113** [comment]
I have had contact with Pablo and he said, that we should use either Singularity or Sarus Containers (https://user.cscs.ch/tools/containers/) because Docker does not work

**Comment by deiruch** [comment]
Am I right assuming that Docker to Singularity is easy?

If so, should we switch?

**Comment by Lukas113** [comment]
I assume it aswell according to https://sylabs.io/guides/2.6/user-guide/singularity_and_docker.html (but if I remember correctly, @cvoegele has already tried something like that and some issues occured)

So according to Pablo I think we don't really have a choice and therefore we have to switch

**Comment by cvoegele** [comment]
Creating a Singularity Image from a Docker image are two simple commands. 
I think the way to go is to still make dockerfiles and simply generate the other image. (Possibly with a Github Action) I have not tried Sarus Containers, but they seem less popular. I am sure there is a reason. Maybe investigate?

The biggest issue I see personally with Singularity containers is that Singularity only runs on linux. They did not implement any emulation layers or vm's like docker and podman did for Windows and Mac. And it is also explicitly only x86_64.

**Comment by Lukas113** [comment]
According to your investigation I think we should continue as you kind of proposed. So keeping docker images for developing and local machines and just build Singularity images from them for CSCS.
