### ISSUE TITLE
Make plot axis in Source Detection notebooks consistent with standard practice

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#70]
(From Marc Audard) Currently, the coordinate axes in the Source Detection notebook is unexpected for scientists: They usually expect the x-axis in the opposite direction. In our notebooks we try to work around this by negating coordinates instead, but then plot them with a positive x-axis:
![image](https://user-images.githubusercontent.com/4119188/161074024-706bb575-c642-4318-b887-88b96a9f0da7.png)

Instead we should not negate coordinates and instead flip the coordinates in our plots.

**Comment by deiruch** [comment]
Related to #20

**Comment by cvoegele** [comment]
@rohitcbscient Does this look better for the explore_sky() ? I think so
![image](https://user-images.githubusercontent.com/10659582/174043351-5b676c69-adbd-43aa-83d2-6e9c2232c3c3.png)

**Comment by rohitcbscient** [comment]
Looks good!
