### ISSUE TITLE
Test Source Detection workflow directly on dirty image (without CLEAN)

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#71]
Slava suggested we should test the source detection workflow directly on the dirty image, without running CLEAN.

**Comment by cvoegele** [comment]
@cvoegele make sure examples work --> DOCUMENTATION

**Comment by deiruch** [comment]
Dirty imager should compute beam size with casa-core (@rohitcbscient knows more), and include it in the output.

**Comment by kenfus** [comment]
Implemented in https://github.com/i4Ds/Karabo-Pipeline/pull/184
