### ISSUE TITLE
Integration of Healpix maps into the sky module for Intensity Mapping

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#74]
(Part of #43)

**Comment by cvoegele** [comment]
Mosaicing -> Interferometer Mode
Driftscan -> Interferometer Mode or Auto Correlated
Multiple pointing -> Auto Correlated

We should have all three modes.
Implement Mosaic mode first, based on discussion  between ETH Team and Rohit. All telescope look at the same spot in one time step, then look at a different one at a different time step.
