### ISSUE TITLE
Support for hdf5 visibilities integration

### ISSUE THREAD

**Issue by rohitcbscient** [i4Ds/Karabo-Pipeline#78]
The task is to integrate visibilities from hdf5 formats to karabo pipeline,

**Comment by rohitcbscient** [comment]
The data structure is the following.
/index_map/freq <HDF5 dataset "freq": shape (16,), type "|V16">
/index_map/pixel <HDF5 dataset "pixel": shape (3145728,), type "<i8">
/index_map/pol <HDF5 dataset "pol": shape (4,), type "|O">
/map <HDF5 dataset "map": shape (16, 4, 3145728), type "<f8">

**Comment by deiruch** [comment]
Add unit tests for this functionality
