### ISSUE TITLE
Doesn't work with Python 3.8

### ISSUE THREAD

**Issue by fschramka** [i4Ds/Karabo-Pipeline#79]
This step failes:
`conda install -c i4ds -c conda-forge karabo-pipeline=0.2.0`

output is:

`(karabo) filip@DESKTOP-UA9FFRS:~$ conda install -c i4ds -c conda-forge karabo-pipeline=0.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -`

And this one is stuck for a loooong loooong time :)

**Comment by cvoegele** [comment]
@fschramka I just tested it with these commands and it works fine

```shell
conda create -n karabo
conda activate karabo
conda install -c i4ds -c conda-forge karabo-pipeline=0.3.0 #or 0.2.0
```

Python 3.8 can conflict now, so its best to not pin python and just let the solver find the python version it wants to use. 
I will update the README and documentation showing this change.

**Comment by fschramka** [comment]
Python 3.8 - but I pinned the version when I created the Conda environment

**Comment by cvoegele** [comment]
Could you try it again without setting the python to 3.8?

**Comment by fschramka** [comment]
@cvoegele Did
 
 Tested on my XPS15 Win 11 Laptop in WSL 2.0

Without pinning and everything - worked  fine :) 

> conda list | grep karabo
> --> karabo-pipeline 0.4.0

> python --version
> --> python 3.9.12

Nice :) Seems to work outside of python 3.8.

**Comment by cvoegele** [comment]
Amazing!
