### ISSUE TITLE
Fix for having to manually set the version of Karabo conda should install

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#80]
Currently, conda always install 0.1.0 of the karabo-pipeline if not defined specifically. To make sure that conda will install the latest version of the karabo-pipeline instead, I propose to label the old releases as /old and remove the /main label of the old releases.
Like this installing the pipeline without a version will install the latest.
And installing the old versions would still be possible with a command like this
```shell
conda install -c i4ds/label/old karabo-pipeline
```

These labels could also be used to label development versions or prerelease versions. To make CD more robust.

**Comment by cvoegele** [comment]
@deiruch What do you think?

**Comment by deiruch** [comment]
I'm strongly in favor of this approach!
